postrm,prerm: check backup success

diff --git a/opkg/postrm.in b/opkg/postrm.in
--- a/opkg/postrm.in
+++ b/opkg/postrm.in
@@ -27,8 +27,12 @@ create_backups()
     if [ -f "$SMF_DIR/$DATABASE_FILE" ]; then 
         # move the configuration files that will be regenerated during the installation
         mkdir -p "$bkp_dir"
-        mv $SMF_DIR/$DATABASE_FILE "$bkp_dir"
-        echo "[POST-RM] ... saved database"
+        cmd_output=$(mv $SMF_DIR/$DATABASE_FILE "$bkp_dir")
+        if [ $? -eq 0 ]; then 
+            echo "[POST-RM] ... saved database successfully"
+        else
+            echo "[POST-RM] ... saving database failed for reason: $cmd_output"
+        fi
     else
         echo "[POST-RM] ... There is no such file $SMF_DIR/$DATABASE_FILE, skipping database backup steps."
     fi
@@ -38,8 +42,12 @@ create_backups()
         # old approach: use ls and grep to get the correct files
         #   config_files=$(ls $SMF_DIR | grep json | grep -v bkp)
         mkdir -p "$bkp_dir"
-        mv "$SMF_DIR/segw_v$VERSION_SHORT.json" "$bkp_dir"
-        echo "[POST-RM] ... saved $SMF_DIR/segw_v$VERSION_SHORT.json"
+        cmd_output=$(mv "$SMF_DIR/segw_v$VERSION_SHORT.json" "$bkp_dir")
+        if [ $? -eq 0 ]; then 
+            echo "[POST-RM] ... saved $SMF_DIR/segw_v$VERSION_SHORT.json successfully"
+        else
+            echo "[POST-RM] ... saving $SMF_DIR/segw_v$VERSION_SHORT.json failed for reason: $cmd_output"
+        fi
     else 
         echo "[POST-RM] ... There is no such file $SMF_DIR/segw_v$VERSION_SHORT.json, skipping this backup step."
     fi
@@ -49,8 +57,12 @@ create_backups()
         # old approach: use ls and grep to get the correct files
         #   config_files=$(ls /usr/local/etc/ | grep cfg | grep -v bkp)
         mkdir -p "$bkp_dir"
-        mv "/usr/local/etc/segw_v$VERSION_SHORT.cfg" "$bkp_dir"
-        echo "[POST-RM] ... saved /usr/local/etc/segw_v$VERSION_SHORT.cfg"
+        cmd_output=$(mv "/usr/local/etc/segw_v$VERSION_SHORT.cfg" "$bkp_dir")
+        if [ $? -eq 0 ]; then 
+            echo "[POST-RM] ... saved /usr/local/etc/segw_v$VERSION_SHORT.cfg successfully"
+        else
+            echo "[POST-RM] ... saving /usr/local/etc/segw_v$VERSION_SHORT.cfg failed for reason: $cmd_output"
+        fi
     else 
         echo "[POST-RM] ... There is no such file /usr/local/etc/segw_v$VERSION_SHORT.cfg, skipping this backup step."
     fi
@@ -86,5 +98,5 @@ main ()
     return 0
 }
 
-# This is the only function call, all worflow and logic is done from within main function
+# This is the only function call, all workflow and logic is done from within main function
 main
diff --git a/opkg/prerm.in b/opkg/prerm.in
--- a/opkg/prerm.in
+++ b/opkg/prerm.in
@@ -27,8 +27,12 @@ create_backups()
         # create database dumps first and then move the database here as well
         # For that we do not need to provide the configuration file, this works universally
         mkdir -p "$bkp_dir"
-        /usr/local/sbin/segw -C/usr/local/etc/segw_v"$VERSION_SHORT".cfg -l > "$bkp_dir/database_dump.txt"
-        echo "[PRE-RM] ... dumped database contents"
+        output=$(/usr/local/sbin/segw -C/usr/local/etc/segw_v"$VERSION_SHORT".cfg -l > "$bkp_dir/database_dump.txt")
+        if [ $? -eq 0 ]; then 
+            echo "[PRE-RM] ... dumped database contents successfully"
+        else
+            echo "[PRE-RM] ... database dump creation failed for reason: $output"
+        fi
     else
         echo "[PRE-RM] ... There is no such file $SMF_DIR/$DATABASE_FILE, skipping database backup steps."
     fi
@@ -82,5 +86,5 @@ main ()
     return 0
 }
 
-# This is the only function call, all worflow and logic is done from within main function
+# This is the only function call, all workflow and logic is done from within main function
 main
